### ISSUE TITLE
Configuring Logstash

### ISSUE THREAD

**Issue by animosity022** [fabianfrz/opnsense-logstash-config#1]
I was trying to see how this works and I was using 18.1.2 now and I was seeing this:

`[2018-02-15T11:37:55,512][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Couldn't find any filter plugin named 'opnsensefilter'. Are you sure this is correct? Trying to load the opnsensefilter filter plugin resulted in this error: Problems loading the requested plugin named opnsensefilter of type filter. Error: NameError NameError"}`

I just wanted to validate if I was missing something easy.

**Comment by fabianfrz** [comment]
Yes, you don't have the logstash plugin opnsensefilter installed and therefore you cannot run this config file.
