### ISSUE TITLE
logstash-plugin: command not found

### ISSUE THREAD

**Issue by olegsidokhmetov** [fabianfrz/opnsense-logstash-config#10]
Hello! I tried to install  `logstash-plugin install logstash-filter-opnsensefilter` but I get error `logstash-plugin: command not found`

```
root@geoip4g:~# logstash-plugin install logstash-filter-opnsensefilter
logstash-plugin: command not found
```

**Comment by fabianfrz** [comment]
It may not be in the path. It should be part of logstash in its bin directory.

If that is the case, you need to add the logstash/bin directory to your system path or you have to use the full path like /path/to/logstash-plugin

I hope that helps.

**Comment by olegsidokhmetov** [comment]
Thank you!

 i did it :)

root@geoip4g:/usr/share/logstash/bin# ./logstash-plugin install logstash-filter-opnsensefilter
Validating logstash-filter-opnsensefilter
Installing logstash-filter-opnsensefilter
Installation successful

P.S. Could you please tell me, can I use this is logs.

```
May  5 12:51:23 ha-proxy02 haproxy[5757]: 79.148.***.***:56951 [05/May/2021:12:47:02.231] fe_HTTPS be_HTTPS/proxy02 1/0/261005 1251 -- 423/390/389/252/0 0/0
May  5 12:51:23 ha-proxy02 haproxy[5757]: 2.139.***.***:58433 [05/May/2021:12:50:53.473] fe_HTTP_ADMIN be_HTTP_ADMIN/proxy01 1/0/30057 627 cD 426/2/1/0/0 0/0
```

for exporting to Grafana dashboard https://grafana.com/grafana/dashboards/12506 

 In the  "Overviews" on page https://grafana.com/grafana/dashboards/12506 I can not understand correctly. 


P.S.2 Ingest geoip processor plugin - Elasticsearch Plugins and Integrations [7.13] 
The geoip processor is now a module and distributed with Elasticsearch by default. See GeoIP processor.

**Comment by fabianfrz** [comment]
no, I have no idea where those logs are coming from. However I may look at some point at the ES thing with the geoip change
