### ISSUE TITLE
Field mapping not working

### ISSUE THREAD

**Issue by BeNeDeLuX** [fabianfrz/opnsense-logstash-config#6]
I´m running a new installed ELK-Stack in Version 7.3.1.

The Syslog data from the OPNsense is running fine into the index, but the fields are not complete mapped.  Syslog_message and message is a single line without fields.
No dest_ip, src_ip. port, src and so on.

Seems there changed something in the new version. Or does the new Syslog-NG from the OPNsense changed the format a bit ? I´m on OPNsense 19.7.3-amd64

Your logstash config is active and the needed filer is also installed.
`root@elk01:/usr/share/logstash/bin# ./logstash-plugin list | grep opn
logstash-filter-opnsensefilter
root@elk01:/usr/share/logstash/bin#
`

Info:
The GeoIP is no more available as extra addon. It is now a base part of the new Kibana Version.
So you have to adjust the doc.

Please tell me if you need more informations.

Thank you!

**Comment by BeNeDeLuX** [comment]
Looks like it has something todo with the new Syslog-NG on the OPNsense 19.7.x.
I´m also running an ELK-Stack with Version 6.8.3 and there is also no field mapping for the Firewall-Logs.

**Comment by BeNeDeLuX** [comment]
Installed a OPNsense 19.1 to compare the two syslog outputs.
Since 19.7.x the complete hostname is also part of the syslog message:

**OPNsense 19.1.x**
<134>Sep  9 13:25:27 filterlog: 73,,,0,vtnet1,match,pass,out,4,0x0,,64,42240,0,none,1,icmp,84,172.16.60.50,8.8.8.8,datalength=64 

**OPNsense 19.7.x**
<134>Sep  9 15:51:22 **host.internal.my-domain.tld** filterlog: 172,,,0,igb0,match,pass,out,4,0x0,,64,10641,0,none,1,icmp,84,192.168.217.2,8.8.8.8,datalength=64

So, the grok filter doesn´t match anymore because of the hostname (if i´m right?!)
Hope this helps.

**Comment by BeNeDeLuX** [comment]
Short fix:

https://github.com/fabianfrz/opnsense-logstash-config/blob/32c46a8fa91eb29fc36879a0e37f325f1cc184af/opnsense.logstash.conf#L15

Add the field for the "Hostname" with OPNsense >=19.7.x
`      match => { "message" => "<%{POSINT:syslog_pri}>%{SYSLOGTIMESTAMP:syslog_timestamp} %{HOSTNAME:hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" `

**Comment by superwinni2** [comment]
Kann ich bestätigen. 
Nach dem Update der OPNsense von 19.1.9 auf 19.7.4_1 wurden bei mir in Kibana ebenfalls nur Uhrzeit angeziegt und sosnt nur  - - - - - -.
Mit dem von @BeNeDeLuX genannten Fix funktioniert es wieder.
EDIT: Es fehlt am schluss noch eine  "}" .

**Comment by fabianfrz** [comment]
habe den PR von @superwinni2 angenommen. Daher kann das Ticket hier geschlossen werden.

PR #7
